#!/usr/bin/env bash
set -euo pipefail

# Versions to be used
declare -A VERSIONS=(
    ["go"]=1.15.15
    ["cni-plugins"]=v0.8.5
    ["conmon"]=v2.0.15
    ["cri-tools"]=v1.18.0
    ["runc"]=v1.0.0-rc10
    ["bats"]=v1.2.0
)
export VERSIONS
